In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\girish\appdata\local\programs\python\python314\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\girish\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\girish\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\girish\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\girish\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\girish\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import os
import json

In [3]:
import pandas as pd
import os

#aggregated_insurance

path1="C:/Users/GIRISH/OneDrive/Desktop/phone pe project/pulse/data/aggregated/insurance/country/india/state"
agg_insurance=os.listdir(path1)

col1={"states":[],"years":[],"quarter":[],"trans_type":[],"trans_amount":[],"trans_count":[]}

for states in agg_insurance:
    prsnt_state=path1 + "/" +states 
    agg_year=os.listdir(prsnt_state)
    
    for year in agg_year:
        current_year=prsnt_state+"/"+year
        agg_file=os.listdir(current_year)

        for files in agg_file:
            c_file=current_year+"/"+files
            data=open(c_file,"r")

            a=json.load(data)
            for i in a["data"]["transactionData"]:
                name=i['name']
                count=i['paymentInstruments'][0]['count']
                amount=i['paymentInstruments'][0]['amount']
                col1["trans_type"].append(name)
                col1["trans_count"].append(count)
                col1["trans_amount"].append(amount)
                col1["states"].append(states)
                col1["years"].append(year)
                col1["quarter"].append(int(files.strip(".json")))


aggregated_insurance=pd.DataFrame(col1)


aggregated_insurance['states']=aggregated_insurance['states'].str.replace("-"," ")
aggregated_insurance["states"]=aggregated_insurance["states"].str.replace('andaman & nicobar islands','Andaman & Nicobar')
aggregated_insurance["states"]=aggregated_insurance["states"].str.title()
aggregated_insurance["states"]=aggregated_insurance["states"].str.replace('Dadra & Nagar Haveli & Daman & Diu','Daman & Diu')

In [4]:

aggregated_insurance

                states years  quarter trans_type  trans_amount  trans_count
0    Andaman & Nicobar  2020        2  Insurance        1360.0            6
1    Andaman & Nicobar  2020        3  Insurance       15380.0           41
2    Andaman & Nicobar  2020        4  Insurance      157975.0          124
3    Andaman & Nicobar  2021        1  Insurance      244266.0          225
4    Andaman & Nicobar  2021        2  Insurance      181504.0          137
..                 ...   ...      ...        ...           ...          ...
677        West Bengal  2023        4  Insurance   100365562.0        72712
678        West Bengal  2024        1  Insurance   104987909.0        79576
679        West Bengal  2024        2  Insurance    89476633.0        67048
680        West Bengal  2024        3  Insurance   107451766.0        77158
681        West Bengal  2024        4  Insurance   120602777.0        91719

[682 rows x 6 columns]

In [46]:
#Aggregated_transaction
path2="C:/Users/GIRISH/OneDrive/Desktop/phone pe project/pulse/data/aggregated/transaction/country/india/state"
ser_path=os.listdir(path2)

col2={"states":[],"years":[],"quarter":[],"trans_count":[],"trans_type":[],"trans_amount":[]}


for states in ser_path:
    cur_states=path2+"/"+states
    agre2_path=os.listdir(cur_states)

    for years in agre2_path:
        cur_year=cur_states+"/"+years
        loc=os.listdir(cur_year)

        for files_1 in loc:
            files_part=cur_year+"/"+files_1
            loc_file=open(files_part,"r")

            b=json.load(loc_file)
            
            for i in b['data']['transactionData']:
                count=i['paymentInstruments'][0]['count']
                amount=i['paymentInstruments'][0]['amount']
                name=i['name']
                col2["states"].append(states)
                col2["years"].append(years)
                col2["quarter"].append(int(files_1.strip(".json")))
                col2["trans_count"].append(count)
                col2["trans_type"].append(name)
                col2["trans_amount"].append(amount)
Aggregated_transaction=pd.DataFrame(col2)
Aggregated_transaction['states']=Aggregated_transaction['states'].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar')
Aggregated_transaction['states']=Aggregated_transaction['states'].str.replace("-"," ")
Aggregated_transaction['states']=Aggregated_transaction['states'] .str.title()                                                                       
Aggregated_transaction['states']=Aggregated_transaction['states'].str.replace('Dadra & Nagar Haveli & Daman & Diu','Daman & Diu')               
Aggregated_transaction

,states,years,quarter,trans_count,trans_type,trans_amount
0,Andaman & Nicobar,2018,1,4200,Recharge & bill payments,1.845307e+06
1,Andaman & Nicobar,2018,1,1871,Peer-to-peer payments,1.213866e+07
2,Andaman & Nicobar,2018,1,298,Merchant payments,4.525072e+05
3,Andaman & Nicobar,2018,1,33,Financial Services,1.060142e+04
4,Andaman & Nicobar,2018,1,256,Others,1.846899e+05
...,...,...,...,...,...,...
5029,West Bengal,2024,4,655100809,Merchant payments,3.892862e+11
5030,West Bengal,2024,4,493217788,Peer-to-peer payments,1.361927e+12
5031,West Bengal,2024,4,76043195,Recharge & bill payments,5.753406e+10
5032,West Bengal,2024,4,2352084,Financial Services,8.472965e+08
5033,West Bengal,2024,4,421806,Others,5.053641e+08

In [47]:
Aggregated_transaction

,states,years,quarter,trans_count,trans_type,trans_amount
0,Andaman & Nicobar,2018,1,4200,Recharge & bill payments,1.845307e+06
1,Andaman & Nicobar,2018,1,1871,Peer-to-peer payments,1.213866e+07
2,Andaman & Nicobar,2018,1,298,Merchant payments,4.525072e+05
3,Andaman & Nicobar,2018,1,33,Financial Services,1.060142e+04
4,Andaman & Nicobar,2018,1,256,Others,1.846899e+05
...,...,...,...,...,...,...
5029,West Bengal,2024,4,655100809,Merchant payments,3.892862e+11
5030,West Bengal,2024,4,493217788,Peer-to-peer payments,1.361927e+12
5031,West Bengal,2024,4,76043195,Recharge & bill payments,5.753406e+10
5032,West Bengal,2024,4,2352084,Financial Services,8.472965e+08
5033,West Bengal,2024,4,421806,Others,5.053641e+08

In [7]:
#Aggregated_user
path3="C:/Users/GIRISH/OneDrive/Desktop/phone pe project/pulse/data/aggregated/user/country/india/state"
agre_path=os.listdir(path3)

col3={"states":[],"years":[],"quarter":[],"trans_count":[],"percentage":[],"Brands":[]}

    
for state in agre_path:
    ad_state=path3+"/"+state
    aggre_state=os.listdir(ad_state)

    for year in aggre_state:
        cur_year=ad_state+"/"+year 
        agre_year=os.listdir(cur_year)

        for files in agre_year:
            cur_files=cur_year+"/"+files
            agre_files=open(cur_files,"r")

            c=json.load(agre_files)
            
            try:
                for i in c['data']['usersByDevice']:
                    count=i['count']
                    brands=i['brand']
                    percentage=i['percentage']

                    col3["Brands"].append(brands)
                    col3["trans_count"].append(count)
                    col3["percentage"].append(percentage)
                    col3["states"].append(state )
                    col3["years"].append(year)
                    col3["quarter"].append(int(files.strip(".json")))
            except:
                pass

Aggregated_user=pd.DataFrame(col3)
Aggregated_user['states']=Aggregated_user['states'].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar')
Aggregated_user['states']=Aggregated_user['states'].str.replace("-"," ")
Aggregated_user['states']=Aggregated_user['states'] .str.title()                                                                       
Aggregated_user['states']=Aggregated_user['states'].str.replace('Dadra & Nagar Haveli & Daman & Diu','Daman & Diu')

In [44]:

Aggregated_user

                 states years  quarter  trans_count  percentage   Brands
0     Andaman & Nicobar  2018        1         1665    0.247033   Xiaomi
1     Andaman & Nicobar  2018        1         1445    0.214392  Samsung
2     Andaman & Nicobar  2018        1          982    0.145697     Vivo
3     Andaman & Nicobar  2018        1          501    0.074332     Oppo
4     Andaman & Nicobar  2018        1          332    0.049258  OnePlus
...                 ...   ...      ...          ...         ...      ...
6727        West Bengal  2022        1       330017    0.015056   Lenovo
6728        West Bengal  2022        1       284678    0.012987  Infinix
6729        West Bengal  2022        1       280347    0.012790     Asus
6730        West Bengal  2022        1       277752    0.012671    Apple
6731        West Bengal  2022        1      2196334    0.100199   Others

[6732 rows x 6 columns]

In [43]:
#Map_insurance
path4="C:/Users/GIRISH/OneDrive/Desktop/phone pe project/pulse/data/map/insurance/hover/country/india/state"
agre_path_4=os.listdir(path4)

col4={"states":[],"years":[],"quarter":[],"district_name":[],"trans_count":[],"trans_amount":[]}

for states in agre_path_4:
    cur_states=path4+"/"+states
    agr_loc=os.listdir(cur_states)


    for years in agr_loc:
        cur_year=cur_states+"/"+years
        agr_lo=os.listdir(cur_year)

        for files in agr_lo:
            cur_file=cur_year+"/"+files
            cur_file_loc=open(cur_file,"r")

            d=json.load(cur_file_loc)
            
            for i in d['data']['hoverDataList']:
                name=i['name']
                count=i['metric'][0]['count']
                amount=i['metric'][0]['amount']
                col4["states"].append(states)
                col4["years"].append(years)
                col4["quarter"].append(int(files.strip(".json")))
                col4["district_name"].append(name)
                col4["trans_count"].append(count)
                col4["trans_amount"].append(amount)
                
Map_insurance=pd.DataFrame(col4)
Map_insurance["states"]=Map_insurance["states"].str.replace("-"," ")
Map_insurance["states"]=Map_insurance["states"].str.title()
Map_insurance["states"]=Map_insurance["states"].str.replace("andaman-&-nicobar-islands",'Andaman & Nicobar')
Map_insurance["states"]=Map_insurance["states"].str.replace('Dadra & Nagar Haveli & Daman & Diu','Dadar & Diu')
Map_insurance

,states,years,quarter,district_name,trans_count,trans_amount
0,Andaman & Nicobar Islands,2020,2,south andaman district,3,795.0
1,Andaman & Nicobar Islands,2020,2,nicobars district,3,565.0
2,Andaman & Nicobar Islands,2020,3,north and middle andaman district,1,281.0
3,Andaman & Nicobar Islands,2020,3,south andaman district,35,13651.0
4,Andaman & Nicobar Islands,2020,3,nicobars district,5,1448.0
...,...,...,...,...,...,...
13871,West Bengal,2024,4,alipurduar district,1023,1613143.0
13872,West Bengal,2024,4,paschim bardhaman district,4945,7005851.0
13873,West Bengal,2024,4,nadia district,3807,5031294.0
13874,West Bengal,2024,4,birbhum district,1818,2423290.0
13875,West Bengal,2024,4,purba medinipur district,3559,4439061.0

In [10]:
Map_insurance

,states,years,quarter,districts,trans_count,trans_amount
0,Andaman & Nicobar Islands,2020,2,south andaman district,3,795.0
1,Andaman & Nicobar Islands,2020,2,nicobars district,3,565.0
2,Andaman & Nicobar Islands,2020,3,north and middle andaman district,1,281.0
3,Andaman & Nicobar Islands,2020,3,south andaman district,35,13651.0
4,Andaman & Nicobar Islands,2020,3,nicobars district,5,1448.0
...,...,...,...,...,...,...
13871,West Bengal,2024,4,alipurduar district,1023,1613143.0
13872,West Bengal,2024,4,paschim bardhaman district,4945,7005851.0
13873,West Bengal,2024,4,nadia district,3807,5031294.0
13874,West Bengal,2024,4,birbhum district,1818,2423290.0
13875,West Bengal,2024,4,purba medinipur district,3559,4439061.0

In [11]:
#Map_Transaction
path5="C:/Users/GIRISH/OneDrive/Desktop/phone pe project/pulse/data/map/transaction/hover/country/india/state"
agree_path=os.listdir(path5)

col5={"states":[],"years":[],"quarter":[],"districts":[],"trans_count":[],"trans_amount":[]}

for states in agree_path:
    cur_states=path5+"/"+states
    agre_list=os.listdir(cur_states)

    for year in agre_list:
        cur_year=cur_states+"/"+year
        agre_path=os.listdir(cur_year)

        for files in agre_path:
            cur_files=cur_year+"/"+files
            check_file=open(cur_files,"r")

            e=json.load(check_file)
            
            for i in e['data']['hoverDataList']:
                name=i['name']
                count=i['metric'][0]['count']
                amount=i['metric'][0]['amount']
                col5["districts"].append(name)
                col5["quarter"].append(int(files.strip(".json")))
                col5["states"].append(states)
                col5["trans_amount"].append(amount)
                col5["trans_count"].append(count)
                col5["years"].append(year)
Map_map=pd.DataFrame(col5)
Map_map['states']=Map_map['states'].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar')
Map_map['states']=Map_map['states'].str.replace("-"," ")
Map_map['states']=Map_map['states'] .str.title()                                                                       
Map_map['states']=Map_map['states'].str.replace('Dadra & Nagar Haveli & Daman & Diu','Daman & Diu')               
Map_map

,states,years,quarter,districts,trans_count,trans_amount
0,Andaman & Nicobar,2018,1,north and middle andaman district,442,9.316631e+05
1,Andaman & Nicobar,2018,1,south andaman district,5688,1.256025e+07
2,Andaman & Nicobar,2018,1,nicobars district,528,1.139849e+06
3,Andaman & Nicobar,2018,2,north and middle andaman district,825,1.317863e+06
4,Andaman & Nicobar,2018,2,south andaman district,9395,2.394824e+07
...,...,...,...,...,...,...
20599,West Bengal,2024,4,alipurduar district,15875637,2.099251e+10
20600,West Bengal,2024,4,paschim bardhaman district,56616799,6.968735e+10
20601,West Bengal,2024,4,nadia district,65274337,1.079320e+11
20602,West Bengal,2024,4,birbhum district,36905213,5.778701e+10
20603,West Bengal,2024,4,purba medinipur district,67833775,1.142771e+11

In [41]:
#map_user
path6="C:/Users/GIRISH/OneDrive/Desktop/phone pe project/pulse/data/map/user/hover/country/india/state"
agr_path=os.listdir(path6)

col6={"states":[],"years":[],"quarter":[],"district_name":[],"reg_user":[],"app_opens":[]}

for states in agr_path:
    cur_states=path6 +"/"+ states
    agr_loc=os.listdir(cur_states)

    for years in agr_loc:
        cur_year=cur_states +"/"+years
        loc=os.listdir(cur_year)

        for files in loc:
            file_o=cur_year+"/"+files
            file_loc=open(file_o,"r")

            f=json.load(file_loc)
            for i in f['data']['hoverData'].items():
                districts=i[0]
                reg_user=i[1]['registeredUsers']
                app_openes=i[1]['appOpens']
                col6["district_name"].append(districts)
                col6["reg_user"].append(reg_user)
                col6["app_opens"].append(app_openes)
                col6["states"].append(states)
                col6["years"].append(years)
                col6["quarter"].append(int(files.strip(".json")))
map_user=pd.DataFrame(col6)
map_user['states']=map_user['states'].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar')
map_user['states']=map_user['states'].str.replace("-"," ")
map_user['states']=map_user['states'] .str.title()                                                                       
map_user['states']=map_user['states'].str.replace('Dadra & Nagar Haveli & Daman & Diu','Daman & Diu')               
map_user

,states,years,quarter,district_name,reg_user,app_opens
0,Andaman & Nicobar,2018,1,north and middle andaman district,632,0
1,Andaman & Nicobar,2018,1,south andaman district,5846,0
2,Andaman & Nicobar,2018,1,nicobars district,262,0
3,Andaman & Nicobar,2018,2,north and middle andaman district,911,0
4,Andaman & Nicobar,2018,2,south andaman district,8143,0
...,...,...,...,...,...,...
20603,West Bengal,2024,4,alipurduar district,475688,31842355
20604,West Bengal,2024,4,paschim bardhaman district,1468252,80543469
20605,West Bengal,2024,4,nadia district,1861738,98740305
20606,West Bengal,2024,4,birbhum district,1114220,73465525
20607,West Bengal,2024,4,purba medinipur district,1717074,108350777

In [42]:

map_user

,states,years,quarter,district_name,reg_user,app_opens
0,Andaman & Nicobar,2018,1,north and middle andaman district,632,0
1,Andaman & Nicobar,2018,1,south andaman district,5846,0
2,Andaman & Nicobar,2018,1,nicobars district,262,0
3,Andaman & Nicobar,2018,2,north and middle andaman district,911,0
4,Andaman & Nicobar,2018,2,south andaman district,8143,0
...,...,...,...,...,...,...
20603,West Bengal,2024,4,alipurduar district,475688,31842355
20604,West Bengal,2024,4,paschim bardhaman district,1468252,80543469
20605,West Bengal,2024,4,nadia district,1861738,98740305
20606,West Bengal,2024,4,birbhum district,1114220,73465525
20607,West Bengal,2024,4,purba medinipur district,1717074,108350777

In [14]:
#Top_insurance
path7="C:/Users/GIRISH/OneDrive/Desktop/phone pe project/pulse/data/top/insurance/country/india/state"
aggre_path=os.listdir(path7)

col7={"states":[],"years":[],"quarter":[],"district_name":[],"Trans_count":[],"trans_amount":[]}


for states in aggre_path:
    cur_state=path7+"/"+states
    cur_state_1=os.listdir(cur_state)

    for year in cur_state_1:
        cur_year=cur_state+"/"+year
        cur_year_loc=os.listdir(cur_year)

        for files in cur_year_loc:
            cur_file=cur_year+"/"+files
            cur_loc=open(cur_file,"r")

            g=json.load(cur_loc)

            for i in g['data']['districts']:
                name=i['entityName']
                count=i['metric']['count']
                amount=i['metric']['amount']               
                col7["district_name"].append(name)
                col7["quarter"].append(int(files.strip(".json")))
                col7["states"].append(states)
                col7["trans_amount"].append(amount)
                col7["Trans_count"].append(count)
                col7["years"].append(year)

Top_insurance=pd.DataFrame(col7)

Top_insurance['states']=Top_insurance['states'].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar')
Top_insurance['states']=Top_insurance['states'].str.replace("-"," ")
Top_insurance['states']=Top_insurance['states'] .str.title()                                                                       
Top_insurance['states']=Top_insurance['states'].str.replace('Dadra & Nagar Haveli & Daman & Diu','Daman & Diu')               
Top_insurance

,states,years,quarter,district_name,Trans_count,trans_amount
0,Andaman & Nicobar,2020,2,nicobars,3,565.0
1,Andaman & Nicobar,2020,2,south andaman,3,795.0
2,Andaman & Nicobar,2020,3,south andaman,35,13651.0
3,Andaman & Nicobar,2020,3,nicobars,5,1448.0
4,Andaman & Nicobar,2020,3,north and middle andaman,1,281.0
...,...,...,...,...,...,...
5603,West Bengal,2024,4,paschim bardhaman,4945,7005851.0
5604,West Bengal,2024,4,paschim medinipur,4155,5405054.0
5605,West Bengal,2024,4,malda,4042,4902098.0
5606,West Bengal,2024,4,nadia,3807,5031294.0
5607,West Bengal,2024,4,purba bardhaman,3595,4482879.0

In [15]:
Top_insurance

,states,years,quarter,district_name,Trans_count,trans_amount
0,Andaman & Nicobar,2020,2,nicobars,3,565.0
1,Andaman & Nicobar,2020,2,south andaman,3,795.0
2,Andaman & Nicobar,2020,3,south andaman,35,13651.0
3,Andaman & Nicobar,2020,3,nicobars,5,1448.0
4,Andaman & Nicobar,2020,3,north and middle andaman,1,281.0
...,...,...,...,...,...,...
5603,West Bengal,2024,4,paschim bardhaman,4945,7005851.0
5604,West Bengal,2024,4,paschim medinipur,4155,5405054.0
5605,West Bengal,2024,4,malda,4042,4902098.0
5606,West Bengal,2024,4,nadia,3807,5031294.0
5607,West Bengal,2024,4,purba bardhaman,3595,4482879.0

In [16]:
#Top_map
path8="C:/Users/GIRISH/OneDrive/Desktop/phone pe project/pulse/data/top/transaction/country/india/state"
agre_path=os.listdir(path8)

col8={"states":[],"years":[],"quarter":[],"district_name":[],"Trans_count":[],"trans_amount":[],"Pin_codes":[]}



for state in agre_path:
    cur_state=path8+"/"+state
    cur_loc=os.listdir(cur_state)

    for year in cur_loc:
        cur_year=cur_state+"/"+year
        cur_year_loc_=os.listdir(cur_year)

        for files in cur_year_loc_:
            cur_files=cur_year+"/"+files
            cur_loc_file=open(cur_files,"r")

            h=json.load(cur_loc_file)
            
            for i in h['data']['pincodes']:
                ent_name=i['entityName']
                count=i['metric']['count']
                amount=i['metric']['amount']

            for j in h['data']['districts']:
                district_name=j['entityName']

                col8["district_name"].append(district_name)
                col8["Pin_codes"].append(ent_name)
                col8["quarter"].append(int(files.strip(".json")))
                col8["states"].append(state)
                col8["trans_amount"].append(amount)
                col8["Trans_count"].append(count)
                col8["years"].append(year)

Top_map=pd.DataFrame(col8)
Top_map['states']=Top_map['states'].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar')
Top_map['states']=Top_map['states'].str.replace("-"," ")
Top_map['states']=Top_map['states'] .str.title()                                                                       
Top_map['states']=Top_map['states'].str.replace('Dadra & Nagar Haveli & Daman & Diu','Daman & Diu')               
Top_map

,states,years,quarter,district_name,Trans_count,trans_amount,Pin_codes
0,Andaman & Nicobar,2018,1,south andaman,168,5.474697e+05,744302
1,Andaman & Nicobar,2018,1,nicobars,168,5.474697e+05,744302
2,Andaman & Nicobar,2018,1,north and middle andaman,168,5.474697e+05,744302
3,Andaman & Nicobar,2018,2,south andaman,291,1.026590e+06,744302
4,Andaman & Nicobar,2018,2,nicobars,291,1.026590e+06,744302
...,...,...,...,...,...,...,...
8291,West Bengal,2024,4,howrah,6313560,1.050259e+10,733134
8292,West Bengal,2024,4,nadia,6313560,1.050259e+10,733134
8293,West Bengal,2024,4,malda,6313560,1.050259e+10,733134
8294,West Bengal,2024,4,hooghly,6313560,1.050259e+10,733134
8295,West Bengal,2024,4,paschim medinipur,6313560,1.050259e+10,733134

In [17]:
#Top_user
import pandas as pd

path9="C:/Users/GIRISH/OneDrive/Desktop/phone pe project/pulse/data/top/user/country/india/state"
agre_path=os.listdir(path9)
col9={"states":[],"district_name":[],"years":[],"quarter":[],"registered_users":[]}
for state in agre_path:
    cur_state=path9+"/"+state
    cur_loc=os.listdir(cur_state)

    for year in cur_loc:
        cur_year=cur_state+"/"+year
        cur_year_loc_=os.listdir(cur_year)

        for files in cur_year_loc_:
            cur_files=cur_year+"/"+files
            cur_loc_file=open(cur_files,"r")

            i=json.load(cur_loc_file)

            for j in i['data']['districts']:
                reg_user=j['registeredUsers']
                district_name=j['name']
                col9["district_name"].append(district_name)
                col9["quarter"].append(int(files.strip(".json")))
                col9["states"].append(state)
                col9["registered_users"].append(reg_user)
                col9["years"].append(year)

Top_user=pd.DataFrame(col9)

Top_user['states']=Top_user['states'].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar')
Top_user['states']=Top_user['states'].str.replace("-"," ")
Top_user['states']=Top_user['states'] .str.title()                                                                       
Top_user['states']=Top_user['states'].str.replace('Dadra & Nagar Haveli & Daman & Diu','Daman & Diu')               
Top_user

,states,district_name,years,quarter,registered_users
0,Andaman & Nicobar,south andaman,2018,1,5846
1,Andaman & Nicobar,north and middle andaman,2018,1,632
2,Andaman & Nicobar,nicobars,2018,1,262
3,Andaman & Nicobar,south andaman,2018,2,8143
4,Andaman & Nicobar,north and middle andaman,2018,2,911
...,...,...,...,...,...
8291,West Bengal,hooghly,2024,4,1957356
8292,West Bengal,nadia,2024,4,1861738
8293,West Bengal,purba medinipur,2024,4,1717074
8294,West Bengal,paschim medinipur,2024,4,1522845
8295,West Bengal,paschim bardhaman,2024,4,1468252

In [18]:
Top_user.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8296 entries, 0 to 8295
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   states            8296 non-null   object
 1   district_name     8296 non-null   object
 2   years             8296 non-null   object
 3   quarter           8296 non-null   int64
 4   registered_users  8296 non-null   int64
dtypes: int64(2), object(3)
memory usage: 324.2+ KB

In [19]:
import mysql.connector as sql

In [20]:
aggregated_insurance.head()

              states years  quarter trans_type  trans_amount  trans_count
0  Andaman & Nicobar  2020        2  Insurance        1360.0            6
1  Andaman & Nicobar  2020        3  Insurance       15380.0           41
2  Andaman & Nicobar  2020        4  Insurance      157975.0          124
3  Andaman & Nicobar  2021        1  Insurance      244266.0          225
4  Andaman & Nicobar  2021        2  Insurance      181504.0          137

In [21]:
mydb=sql.connect(
    host='localhost',
    user='root',
    password='GirishGidda@2002',
    database='phone_pe_t_i',
    port="3306",
    auth_plugin='mysql_native_password'
)
cursor=mydb.cursor()
create_query_1='''CREATE TABLE if not exists aggregated_insurance(states varchar(255),
                                                    years int,
                                                    quarter int,
                                                    trans_type varchar(255),
                                                    trans_amont bigint,
                                                    trans_count bigint)'''
cursor.execute(create_query_1)
mydb.commit()
insert_query_1= '''insert into aggregated_insurance(states,years,quarter,trans_type,trans_amount,trans_count)
                                                    values(%s,%s,%s,%s,%s,%s)'''
val=aggregated_insurance.values.tolist()
cursor.executemany(insert_query_1,val)
mydb.commit()

In [22]:
Aggregated_transaction

,states,years,quarter,trans_count,trans_name,trans_amount
0,Andaman & Nicobar,2018,1,4200,Recharge & bill payments,1.845307e+06
1,Andaman & Nicobar,2018,1,1871,Peer-to-peer payments,1.213866e+07
2,Andaman & Nicobar,2018,1,298,Merchant payments,4.525072e+05
3,Andaman & Nicobar,2018,1,33,Financial Services,1.060142e+04
4,Andaman & Nicobar,2018,1,256,Others,1.846899e+05
...,...,...,...,...,...,...
5029,West Bengal,2024,4,655100809,Merchant payments,3.892862e+11
5030,West Bengal,2024,4,493217788,Peer-to-peer payments,1.361927e+12
5031,West Bengal,2024,4,76043195,Recharge & bill payments,5.753406e+10
5032,West Bengal,2024,4,2352084,Financial Services,8.472965e+08
5033,West Bengal,2024,4,421806,Others,5.053641e+08

In [23]:
mydb=sql.connect(
    host='localhost',
    user='root',
    password='GirishGidda@2002',
    database='phone_pe_t_i',
    port="3306",
    auth_plugin='mysql_native_password'
)
cursor=mydb.cursor()

In [49]:
create_query_2='''CREATE TABLE if not exists Aggregated_transaction(states varchar(255),
                                                                    years int,
                                                                    quarter int,
                                                                    trans_count bigint,
                                                                    trans_type varchar(255),
                                                                    trans_amount bigint)'''
                                                   
cursor.execute(create_query_2)
mydb.commit()
insert_query_2= '''insert into Aggregated_transaction(states,years,quarter,trans_count,trans_type,trans_amount)
                                                    values(%s,%s,%s,%s,%s,%s)'''
data=Aggregated_transaction.values.tolist()
cursor.executemany(insert_query_2,data)
mydb.commit()

ProgrammingError: 1054 (42S22): Unknown column 'trans_type' in 'field list'

In [25]:
Aggregated_transaction

,states,years,quarter,trans_count,trans_name,trans_amount
0,Andaman & Nicobar,2018,1,4200,Recharge & bill payments,1.845307e+06
1,Andaman & Nicobar,2018,1,1871,Peer-to-peer payments,1.213866e+07
2,Andaman & Nicobar,2018,1,298,Merchant payments,4.525072e+05
3,Andaman & Nicobar,2018,1,33,Financial Services,1.060142e+04
4,Andaman & Nicobar,2018,1,256,Others,1.846899e+05
...,...,...,...,...,...,...
5029,West Bengal,2024,4,655100809,Merchant payments,3.892862e+11
5030,West Bengal,2024,4,493217788,Peer-to-peer payments,1.361927e+12
5031,West Bengal,2024,4,76043195,Recharge & bill payments,5.753406e+10
5032,West Bengal,2024,4,2352084,Financial Services,8.472965e+08
5033,West Bengal,2024,4,421806,Others,5.053641e+08

In [26]:
create_query_3='''CREATE TABLE if not exists Aggregated_user(states varchar(255),
                                                             years int,
                                                             quarter int,
                                                             trans_count bigint,
                                                             percentage float,
                                                             Brands varchar(255))'''
                                                   
cursor.execute(create_query_3)
mydb.commit()
insert_query_3= '''insert into Aggregated_user(states,years,quarter,trans_count,percentage,Brands)
                                                values(%s,%s,%s,%s,%s,%s)'''
data1=Aggregated_user.values.tolist()
cursor.executemany(insert_query_3,data1)
mydb.commit()

In [27]:
Aggregated_user

                 states years  quarter  trans_count  percentage   Brands
0     Andaman & Nicobar  2018        1         1665    0.247033   Xiaomi
1     Andaman & Nicobar  2018        1         1445    0.214392  Samsung
2     Andaman & Nicobar  2018        1          982    0.145697     Vivo
3     Andaman & Nicobar  2018        1          501    0.074332     Oppo
4     Andaman & Nicobar  2018        1          332    0.049258  OnePlus
...                 ...   ...      ...          ...         ...      ...
6727        West Bengal  2022        1       330017    0.015056   Lenovo
6728        West Bengal  2022        1       284678    0.012987  Infinix
6729        West Bengal  2022        1       280347    0.012790     Asus
6730        West Bengal  2022        1       277752    0.012671    Apple
6731        West Bengal  2022        1      2196334    0.100199   Others

[6732 rows x 6 columns]

In [28]:
create_query_4='''CREATE TABLE if not exists Map_insurance(states varchar(255),
                                                            years int,
                                                            quarter int,
                                                            districts varchar(255),
                                                            trans_count bigint,
                                                            trans_amount bigint)'''
                                                   
cursor.execute(create_query_4)
mydb.commit()
insert_query_4= '''insert into Map_insurance(states,years,quarter,districts,trans_count,trans_amount)
                                                values(%s,%s,%s,%s,%s,%s)'''
data=Map_insurance.values.tolist()
cursor.executemany(insert_query_4,data)
mydb.commit()

In [29]:
Map_insurance

,states,years,quarter,districts,trans_count,trans_amount
0,Andaman & Nicobar Islands,2020,2,south andaman district,3,795.0
1,Andaman & Nicobar Islands,2020,2,nicobars district,3,565.0
2,Andaman & Nicobar Islands,2020,3,north and middle andaman district,1,281.0
3,Andaman & Nicobar Islands,2020,3,south andaman district,35,13651.0
4,Andaman & Nicobar Islands,2020,3,nicobars district,5,1448.0
...,...,...,...,...,...,...
13871,West Bengal,2024,4,alipurduar district,1023,1613143.0
13872,West Bengal,2024,4,paschim bardhaman district,4945,7005851.0
13873,West Bengal,2024,4,nadia district,3807,5031294.0
13874,West Bengal,2024,4,birbhum district,1818,2423290.0
13875,West Bengal,2024,4,purba medinipur district,3559,4439061.0

In [30]:
create_query_5='''CREATE TABLE if not exists Map_map(states varchar(255),
                                                     years int,
                                                     quarter int,
                                                     districts varchar(255),
                                                     trans_count bigint,
                                                     trans_amount bigint)'''
                                                   
cursor.execute(create_query_5)
mydb.commit()
insert_query_5= '''insert into Map_map(states,years,quarter,districts,trans_count,trans_amount)
                                                values(%s,%s,%s,%s,%s,%s)'''
data3=Map_map.values.tolist()
cursor.executemany(insert_query_5,data3)
mydb.commit()

In [50]:
Map_Transaction

NameError: name 'Map_Transaction' is not defined

In [48]:
create_query_6='''CREATE TABLE if not exists map_user(states varchar(255),
                                                      years int,
                                                      quarter int,
                                                      district_name varchar(255),
                                                      reg_user bigint,
                                                      app_opens bigint)'''
                                                   
cursor.execute(create_query_6)
mydb.commit()
insert_query_6= '''insert into map_user(states,years,quarter,district_name,reg_user,app_opens)
                                                values(%s,%s,%s,%s,%s,%s)'''
data4=map_user.values.tolist()
cursor.executemany(insert_query_6,data4)
mydb.commit()

ProgrammingError: 1054 (42S22): Unknown column 'district_name' in 'field list'

In [33]:
map_user

,states,years,quarter,districts,reg_user,app_opens
0,Andaman & Nicobar,2018,1,north and middle andaman district,632,0
1,Andaman & Nicobar,2018,1,south andaman district,5846,0
2,Andaman & Nicobar,2018,1,nicobars district,262,0
3,Andaman & Nicobar,2018,2,north and middle andaman district,911,0
4,Andaman & Nicobar,2018,2,south andaman district,8143,0
...,...,...,...,...,...,...
20603,West Bengal,2024,4,alipurduar district,475688,31842355
20604,West Bengal,2024,4,paschim bardhaman district,1468252,80543469
20605,West Bengal,2024,4,nadia district,1861738,98740305
20606,West Bengal,2024,4,birbhum district,1114220,73465525
20607,West Bengal,2024,4,purba medinipur district,1717074,108350777

In [34]:
create_query_7='''CREATE TABLE if not exists Top_insurance(states varchar(255),
                                                            years int,
                                                            quarter int,
                                                            district_name varchar(255),
                                                            Trans_count bigint,
                                                            trans_amount bigint)'''
                                                   
cursor.execute(create_query_7)
mydb.commit()
insert_query_7= '''insert into Top_insurance(states,years,quarter,district_name,Trans_count,trans_amount)
                                                values(%s,%s,%s,%s,%s,%s)'''
data5=Top_insurance.values.tolist()
cursor.executemany(insert_query_7,data5)
mydb.commit()

In [35]:
Top_insurance

,states,years,quarter,district_name,Trans_count,trans_amount
0,Andaman & Nicobar,2020,2,nicobars,3,565.0
1,Andaman & Nicobar,2020,2,south andaman,3,795.0
2,Andaman & Nicobar,2020,3,south andaman,35,13651.0
3,Andaman & Nicobar,2020,3,nicobars,5,1448.0
4,Andaman & Nicobar,2020,3,north and middle andaman,1,281.0
...,...,...,...,...,...,...
5603,West Bengal,2024,4,paschim bardhaman,4945,7005851.0
5604,West Bengal,2024,4,paschim medinipur,4155,5405054.0
5605,West Bengal,2024,4,malda,4042,4902098.0
5606,West Bengal,2024,4,nadia,3807,5031294.0
5607,West Bengal,2024,4,purba bardhaman,3595,4482879.0

In [36]:
create_query_8='''CREATE TABLE if not exists Top_map(states varchar(255),
                                                            years int,
                                                            quarter int,
                                                            district_name varchar(255),
                                                            Trans_count bigint,
                                                            trans_amount bigint,
                                                            Pin_codes bigint)'''
                                                   
cursor.execute(create_query_8)
mydb.commit()
insert_query_8= '''insert into Top_map(states,years,quarter,district_name,Trans_count,trans_amount,Pin_codes)
                                                values(%s,%s,%s,%s,%s,%s,%s)'''
data6=Top_map.values.tolist()
cursor.executemany(insert_query_8,data6)
mydb.commit()

In [37]:
Top_map

,states,years,quarter,district_name,Trans_count,trans_amount,Pin_codes
0,Andaman & Nicobar,2018,1,south andaman,168,5.474697e+05,744302
1,Andaman & Nicobar,2018,1,nicobars,168,5.474697e+05,744302
2,Andaman & Nicobar,2018,1,north and middle andaman,168,5.474697e+05,744302
3,Andaman & Nicobar,2018,2,south andaman,291,1.026590e+06,744302
4,Andaman & Nicobar,2018,2,nicobars,291,1.026590e+06,744302
...,...,...,...,...,...,...,...
8291,West Bengal,2024,4,howrah,6313560,1.050259e+10,733134
8292,West Bengal,2024,4,nadia,6313560,1.050259e+10,733134
8293,West Bengal,2024,4,malda,6313560,1.050259e+10,733134
8294,West Bengal,2024,4,hooghly,6313560,1.050259e+10,733134
8295,West Bengal,2024,4,paschim medinipur,6313560,1.050259e+10,733134

In [38]:
create_query_9='''CREATE TABLE if not exists Top_user(states varchar(255),
                                                        district_name varchar(255),
                                                        years int,
                                                        quarter int,
                                                        registered_users bigint)'''
                                                   
cursor.execute(create_query_9)
mydb.commit()
insert_query_9= '''insert into Top_user(states,district_name,years,quarter,registered_users)
                                                values(%s,%s,%s,%s,%s)'''
data7=Top_user.values.tolist()
cursor.executemany(insert_query_9,data7)
mydb.commit()

In [39]:
"hi"

'hi'

In [40]:
Aggregated_Insurance
Aggregated_Transaction
Aggregated_User




Map_Insurance
Map_User
Top_Insurance

Top_Insurance
Top_Map
Top_User

NameError: name 'Aggregated_Insurance' is not defined

In [ ]:
import os
import json

top_user_district_path = r"C:\Users\GIRISH\OneDrive\Desktop\pulse\data\top\users\district"

for state in os.listdir(top_user_district_path):
    state_path = os.path.join(top_user_district_path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):
            if file.endswith(".json"):
                quarter = int(file.strip(".json"))
                file_path = os.path.join(year_path, file)

                with open(file_path, "r") as f:
                    data = json.load(f)

                districts = data.get("data", {}).get("districts", [])

                for d in districts:
                    district_name = d.get("name")
                    metric = d.get("metric", {})

                    # ✅ THE REAL FIX IS HERE
                    registered_users = metric.get("registeredUsers", 0)
                    app_opens = metric.get("appOpens", 0)

                    cursor.execute("""
                        INSERT INTO top_user_district
                        (State, district_name, Years, Quarter, Registered_Users, App_Opens)
                        VALUES (%s, %s, %s, %s, %s, %s)
                    """, (
                        state.replace("-", " "),
                        district_name,
                        int(year),
                        quarter,
                        registered_users,
                        app_opens
                    ))

mydb.commit()